-- ==============================================================================
-- MAYORISTA360 — SIN DATOS SEMILLA
-- ==============================================================================
-- Este proyecto arranca con el catálogo en BLANCO a propósito.
-- El dueño del negocio crea desde cero sus categorías, productos y preventistas
-- desde el Panel de Administración (o importa un respaldo JSON).
--
-- Para usar la app solo necesitás correr supabase/schema.sql una vez.
-- NO hace falta ejecutar este archivo.
-- ==============================================================================
